const CartActionTypes = {
  TOGGLE_CART_HIDEEN: 'TOGGLE_CART_HIDEEN',
  ADD_ITEM: 'ADD_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_CART: 'CLEAR_CART'
};
export default CartActionTypes;
